FROM node:alpine

RUN npm install @angular/cli -g

WORKDIR /app/frontend

COPY package.json .

RUN npm install

COPY . .

# CMD ["ng","serve"]
CMD ["ng","serve","--host", "0.0.0.0", "--disable-host-check"]